// <auto-generated />
using System;
using LexiconMovies.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LexiconMovies.Migrations
{
    [DbContext(typeof(LexiconMoviesContext))]
    [Migration("20190124130248_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LexiconMovies.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Genre");

                    b.Property<decimal>("Price");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Science Fiction",
                            Price = 140m,
                            ReleaseDate = new DateTime(2002, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "AI"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Comedy",
                            Price = 120m,
                            ReleaseDate = new DateTime(2018, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "AI FTW"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Drama",
                            Price = 160m,
                            ReleaseDate = new DateTime(2009, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Generations"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Splatter",
                            Price = 80m,
                            ReleaseDate = new DateTime(1989, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Return of the Killer Penguins"
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Splatter",
                            Price = 60m,
                            ReleaseDate = new DateTime(1964, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Killer Penguins from Space"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
